services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ApiKey=${API_KEY}
      - DocsContentPath=/docs-content
      - AllowedOrigins__0=http://localhost:8070
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - MaIN__GeminiKey=${GEMINI_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
    volumes:
      - ./docs-content:/docs-content:ro
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "8070:80"
    depends_on:
      - backend
